---

- name: Install NBIS software
  hosts: hadoopnodes
  vars:
    nbis_prefix: "/usr/local"
    nbis_configure_args: "--64 --without-X11"
    nbis_version: "5.0.0"
    nbis_src_url: "http://nigos.nist.gov:8080/nist/nbis/nbis_v{{ nbis_version | replace('.', '_') }}.zip"
    nbis_src_zip: "{{ nbis_src_url | basename }}"
    nbis_src_checksum: "sha256:0adf8ab0f6b0e4208de50ca00ba21d3d77112ecd66288757ddfed21f6bee92c3"
    nbis_src_name: "{{ nbis_src_zip | splitext | first }}"

  tasks:

    ##################################################
    # Debian
    ##################################################

    - name: add repository keys (Debian)
      when: ansible_os_family == 'Debian'
      become: yes
      apt_key:
        keyserver: "keyserver.ubuntu.com"
        id: "642AC823"
        state: present

    - name: add repositories (Debian)
      when: ansible_os_family == 'Debian'
      become: yes
      apt_repository:
        repo: "deb https://dl.bintray.com/sbt/debian /"
        state: present
        update_cache: yes

    - name: install dependencies (Debian)
      when: ansible_os_family == 'Debian'
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - cmake
        - unzip
        - sbt

    ##################################################
    # RedHat
    ##################################################

    - name: add repository (RedHat)
      when: ansible_os_family == 'RedHat'
      become: yes
      get_url:
        url: "https://bintray.com/sbt/rpm/rpm"
        dest: /etc/yum.repos.d/binary-sbt-rpm.repo

    - name: install dependencies (RedHat)
      when: ansible_os_family == 'RedHat'
      become: yes
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - cmake
        - unzip

    - name: install dependencies (unsigned packages) (RedHat)
      when: ansible_os_family == 'RedHat'
      become: yes
      yum:
        name: "{{ item }}"
        state: present
        disable_gpg_check: yes
      with_items:
        - sbt


    ##################################################

    - name: download NBIS
      get_url:
        url: "{{ nbis_src_url }}"
        dest: "/tmp"
        checksum: "{{ nbis_src_checksum }}"

    - name: extract
      unarchive:
        src: "/tmp/{{ nbis_src_zip }}"
        dest: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/Rel_{{ nbis_version }}"
        copy: no

    - name: configure and build
      shell: "{{ item.cmd }} && touch {{ item.creates }}"
      args:
        chdir: "{{ ansible_env.HOME }}/Rel_{{ nbis_version }}"
        creates: "{{ item.creates }}"
      with_items:
        - cmd: "./setup.sh {{ nbis_prefix }} {{ nbis_configure_args }}"
          creates: .ran-setup.sh
        - cmd: "make config"
          creates: .ran-make:config
        - cmd: "make it"
          creates: .ran-make:it

    - name: install
      become: yes
      shell: "make install && touch .ran-make:install"
      args:
        chdir: "{{ ansible_env.HOME }}/Rel_{{ nbis_version }}"
        creates: ".ran-make:install"


######################################################################

- name: Deploy analysis code
  become: yes
  become_user: hadoop
  hosts: frontendnodes
  tasks:
    - name: send project
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}"
      with_items:
        - project
        - NBIS.sbt
        - NBIS.scala

